apiVersion: v1
kind: DaemonSet
metadata:
  name: Producteur
spec:
  selector:
    matchLabels:
      name: daemon
  template:
    metadata:
      labels:
        name: daemon
    spec:
      containers:
      - name: alpine
        image: alpine:3.12.4
        command: ["sleep","3600"]
        volumeMounts:
        - name: alpine
          mountPath: /data/web
       volumes:
       - name: data
         hostPath: /data/
