apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: producteur
spec:
  selector:
    matchLabels:
      name: daemonset-index
  template:
    metadata:
      labels:
        name: daemonset-index
    spec:
      containers:
      - name: alpine
        image: alpine:3.13.4
        volumeMounts:
        - name: volume-web
          mountPath: /data/web
      volumes:
      - name: volume-web
        hostPath: 
          path: /data/web
          type: DirectoryOrCreate
